######################################################################################

# Linear bounding volume hierarchy data structures and constructors in Metal
#     by Wei-Shan Su,
#     July 13, 2026

######################################################################################
################# Constructing LBVH #################
"""
    LinearBVH(enc :: MortonEncoding, scale, ::Val{ThreadsPerGroup}=Val(256))
    LinearBVH(enc :: MortonEncoding, scale, leaf_min, leaf_max, ::Val{ThreadsPerGroup}=Val(256))

Construct a linear bounding volume hierarchy directly from Morton-sorted data.
The hierarchy topology is generated by bottom-up subtree merging, while internal
axis-aligned bounding boxes and maximum scale values are accumulated from the
leaf nodes.

The two-argument form represents each leaf by the point stored in `enc.coord`.
The four-argument form accepts explicit minimum and maximum coordinates for
each leaf bounding box. All supplied arrays must already follow the Morton
ordering used by `enc.codes`.

# Parameters
- `enc :: MortonEncoding`: Morton-sorted codes and coordinates defining the leaf ordering.
- `scale`: Per-leaf scale values arranged in Morton order.
- `leaf_min`: Per-dimension minimum coordinates of the leaf bounding boxes, arranged in Morton order.
- `leaf_max`: Per-dimension maximum coordinates of the leaf bounding boxes, arranged in Morton order.
- `::Val{ThreadsPerGroup}`: Number of threads used by the Metal kernels.

# Returns
- `LinearBVH`: Immutable hierarchy containing the stackless tree topology,
    unified node bounding boxes, and hierarchical maximum scale values.
"""
function Partia.LinearBVH(enc :: MortonEncoding{D, Float32, TI, MtlVector{Float32}, MtlVector{TI}}, scale :: MtlVector{Float32}, leaf_min :: NTuple{D, MtlVector{Float32}}, leaf_max :: NTuple{D, MtlVector{Float32}}, :: Val{ThreadsPerGroup} = Val(256)) where {D, ThreadsPerGroup, TI <: Unsigned}
    # Here we assume scale, leaf_min and leaf_max have been sorted using the same Morton ordering.
    codes = enc.codes
    n = length(codes)
    length(scale) == n || throw(DimensionMismatch("scale and enc.codes must have identical lengths"))
    @inbounds for d in 1:D
        length(leaf_min[d]) == n || throw(DimensionMismatch("leaf_min[$d] and enc.codes must have identical lengths"))
        length(leaf_max[d]) == n || throw(DimensionMismatch("leaf_max[$d] and enc.codes must have identical lengths"))
    end

    n >= 1 || throw(ArgumentError("LinearBVH: enc.codes must be non-empty (got n=0)."))
    issorted(codes) || throw(ArgumentError("LinearBVH: enc.codes must be sorted in nondecreasing order."))

    # Int32 node-ID capacity: 2n - 1 must fit in Int32.
    n_max = (typemax(Int32) ÷ 2) + 1
    n <= n_max || throw(ArgumentError("LinearBVH: n=$n exceeds the Int32 node-ID capacity (requires 2n-1 ≤ typemax(Int32); n ≤ $n_max)."))

    n_internal = n - 1
    total_length = 2n - 1

    # Allocate topology and unified node data.
    left = MtlVector{Int32}(undef, n_internal)
    escape = Metal.zeros(Int32, total_length)
    aabb = Partia.AABB{D, Float32, MtlVector{Float32}}(ntuple(_ -> MtlVector{Float32}(undef, total_length), D), ntuple(_ -> MtlVector{Float32}(undef, total_length), D))
    unified_scale = MtlVector{Float32}(undef, total_length)

    # Initialise the leaf section: unified leaf IDs are n:(2n - 1).
    @metal threads=(ThreadsPerGroup,) groups=(cld(n, ThreadsPerGroup),) Partia.LinearBoundingVolumeHierarchy._initialize_leaf_node!(unified_scale, aabb, scale, leaf_min, leaf_max, n_internal)
    # Metal commands submitted to the same queue are ordered, so the
    # construction kernel below needs no intermediate host-side barrier.

    # Construct the LBVH storage.
    lbvh = Partia.LinearBVH{D, Float32, MtlVector{Float32}, MtlVector{Int32}}(n, left, escape, aabb, unified_scale)

    # Temporary rendezvous storage indexed by split position.
    # Zero indicates that no child subtree has reached this slot yet.
    store = Metal.zeros(Int32, n_internal)

    if n_internal > 0
        # Build the topology and unified node data by bottom-up merging.
        @metal threads=(ThreadsPerGroup,) groups=(cld(n, ThreadsPerGroup),) Partia.LinearBoundingVolumeHierarchy._ascend_from_leaf!(lbvh, store, codes)
        Metal.synchronize()
    end

    return lbvh
end

function Partia.LinearBVH(enc :: MortonEncoding{D, Float32, TI, MtlVector{Float32}, MtlVector{TI}}, scale :: MtlVector{Float32}, :: Val{ThreadsPerGroup} = Val(256)) where {D, ThreadsPerGroup, TI <: Unsigned}
    return Partia.LinearBVH(enc, scale, enc.coord, enc.coord, Val(ThreadsPerGroup))
end
