######################################################################################

# Linear bounding volume hierarchy data structures and constructors.
#     by Wei-Shan Su,
#     May 4, 2026

######################################################################################
struct LinearBVH{D, TF <: AbstractFloat, VF <: AbstractVector{TF}, VI <: AbstractVector{Int32}}
    # Binary Radix Tree
    nleaf  :: Int

    # Topology
    left   :: VI                     # length = nleaf-1, for internal node only
    escape :: VI                     # length = 2*nleaf-1

    # AABB
    aabb  :: AABB{D, TF, VF}         # length = 2*nleaf-1
    scale :: VF                      # length = 2*nleaf-1
end

function Adapt.adapt_structure(to, x :: LBVH) where {D, LBVH <: LinearBVH{D}}
    LinearBVH(
        x.nleaf,
        Adapt.adapt(to, x.left),
        Adapt.adapt(to, x.escape),
        Adapt.adapt(to, x.aabb),
        Adapt.adapt(to, x.scale),
    )
end

################# Constructing LBVH #################
"""
    LinearBVH(enc :: MortonEncoding, scale)
    LinearBVH(enc :: MortonEncoding, scale, leaf_min, leaf_max)

Construct a linear bounding volume hierarchy directly from Morton-sorted data.
The hierarchy topology is generated by bottom-up subtree merging, while internal
axis-aligned bounding boxes and maximum scale values are accumulated from the
leaf nodes.

The two-argument form represents each leaf by the point stored in `enc.coord`.
The four-argument form accepts explicit minimum and maximum coordinates for
each leaf bounding box. All supplied arrays must already follow the Morton
ordering used by `enc.codes`.

# Parameters
- `enc :: MortonEncoding`: Morton-sorted codes and coordinates defining the leaf ordering.
- `scale`: Per-leaf scale values arranged in Morton order.
- `leaf_min`: Per-dimension minimum coordinates of the leaf bounding boxes, arranged in Morton order.
- `leaf_max`: Per-dimension maximum coordinates of the leaf bounding boxes, arranged in Morton order.

# Returns
- `LinearBVH`: Immutable hierarchy containing the stackless tree topology,
    unified node bounding boxes, and hierarchical maximum scale values.
"""
function LinearBVH(enc :: MortonEncoding{D, TF, TI, Vector{TF}, Vector{TI}}, scale :: Vector{TF}, leaf_min :: NTuple{D, Vector{TF}}, leaf_max :: NTuple{D, Vector{TF}}) where {D, TF <: AbstractFloat, TI <: Unsigned}
    # Here we assume scale, leaf_min and leaf_max have been sorted using the same Morton ordering.
    codes = enc.codes
    n = length(codes)
    length(scale) == n || throw(DimensionMismatch("scale and enc.codes must have identical lengths"))
    @inbounds for d in 1:D
        length(leaf_min[d]) == n || throw(DimensionMismatch("leaf_min[$d] and enc.codes must have identical lengths"))
        length(leaf_max[d]) == n || throw(DimensionMismatch("leaf_max[$d] and enc.codes must have identical lengths"))
    end

    n >= 1 || throw(ArgumentError("LinearBVH: enc.codes must be non-empty (got n=0)."))
    issorted(codes) || throw(ArgumentError("LinearBVH: enc.codes must be sorted in nondecreasing order."))

    # Int32 node-ID capacity: 2n - 1 must fit in Int32.
    n_max = (typemax(Int32) ÷ 2) + 1
    n <= n_max || throw(ArgumentError("LinearBVH: n=$n exceeds the Int32 node-ID capacity (requires 2n-1 ≤ typemax(Int32); n ≤ $n_max)."))

    n_internal = n - 1
    total_length = 2n - 1

    # Allocate topology and unified node data.
    left = Vector{Int32}(undef, n_internal)
    escape = Vector{Int32}(undef, total_length)
    escape[1] = zero(Int32)
    aabb = AABB{D, TF, Vector{TF}}(ntuple(_ -> Vector{TF}(undef, total_length), D), ntuple(_ -> Vector{TF}(undef, total_length), D))
    unified_scale = Vector{TF}(undef, total_length)

    # Construct the LBVH storage.
    lbvh = LinearBVH{D, TF, Vector{TF}, Vector{Int32}}(n, left, escape, aabb, unified_scale)

    # Temporary rendezvous storage indexed by split position.
    # Zero indicates that no child subtree has reached this slot yet.
    store = zeros(Int32, n_internal)
    build!(lbvh, store, enc, scale, leaf_min, leaf_max)
    return lbvh
end

function LinearBVH(enc :: MortonEncoding{D, TF, TI, Vector{TF}, Vector{TI}}, scale :: Vector{TF}) where {D, TF <: AbstractFloat, TI <: Unsigned}
    return LinearBVH(enc, scale, enc.coord, enc.coord)
end
